Add accessibility needs to locker_application
pulibrary/lockers_and_study_spaces pull request #177
Opened 2023-02-09 19:51 UTC by maxkadel

- Currently multi-select but does not allow user to type in answer

Co-authored-by: Ryan Laddusaw <rladdusaw@users.noreply.github.com>

2023-02-13 17:48 UTC, sandbergja requested changes
Looks good, @maxkadel .  I have one concern, though.  Any existing applications where the "accessible" checkbox was checked now no longer display on the locker assignment page.

For example: https://lockers-and-study-spaces-staging.princeton.edu/locker_applications/835/assign -- the user requested an accessible locker before this branch was deployed, but it doesn't display on this screen, so the staff member wouldn't know about their request.

2023-02-13 18:01 UTC, maxkadel commented
> Looks good, @maxkadel . I have one concern, though. Any existing applications where the "accessible" checkbox was checked now no longer display on the locker assignment page.
> 
> For example: https://lockers-and-study-spaces-staging.princeton.edu/locker_applications/835/assign -- the user requested an accessible locker before this branch was deployed, but it doesn't display on this screen, so the staff member wouldn't know about their request.

Thanks @sandbergja , that's a good point. I can see two ways of addressing that:

1. Add a migration that adds unspecified "Accessible: true" to some value in the new `accessibility_needs` field - e.g. `['Unspecified accessibility need]` or something like that
2. Display both the old Accessible boolean and the new accessibility_needs array on the show view

2023-02-13 18:55 UTC, sandbergja commented
Thanks, @maxkadel !

>     1. Add a migration that adds unspecified "Accessible: true" to some value in the new `accessibility_needs` field - e.g. `['Unspecified accessibility need]` or something like that

I like option 1 better — it seems like a less complex ui, and make it easier if we wanted to remove the boolean field eventually.

2023-02-13 21:56 UTC, sandbergja reviewed
Just one thought on the migration before running it on staging.  Not a blocker.

2023-02-13 21:56 UTC, sandbergja commented on app/models/locker_application.rb
> +    LockerApplication.where(accessible: true).find_each do |application|
I believe the accessibility info is used only when assigning lockers.  So, if we don't want to touch as many rows in the migration, we could just select applications that don't yet have an assignment.

2023-02-14 18:31 UTC, sandbergja requested changes
Thanks, @maxkadel !  Two smaller issues I found in the UI today:

- Extra bullet point in the list of accessibility needs at https://lockers-and-study-spaces-staging.princeton.edu/locker_applications/860/assign
- When you attempt to edit an existing application with accessibility needs specified (e.g. https://lockers-and-study-spaces-staging.princeton.edu/locker_applications/860/edit), the existing accessibility needs do not display

2023-02-14 21:32 UTC, sandbergja approved these changes
Great feature, nice implementation.  Thanks, @maxkadel !  🦄🦄🦄

2023-02-14 21:33 UTC, merged