Adding renewal emails and templates
pulibrary/lockers_and_study_spaces pull request #211
Opened 2023-03-08 21:56 UTC by rladdusaw

Resolves #201

2023-03-09 20:35 UTC, kevinreiss requested changes

2023-03-09 20:35 UTC, kevinreiss commented on app/views/user_mailer/lewis_locker_renewal.html.erb
> +<p>Hi,</p>
Sylvia asks for this text to be used here:
```
Your locker privileges expire on <%= @assignment.expiration_date %>. If you would like to renew your locker, please email lewislib@Princeton.edu Please remember if your status changes during the year from enrolled to on leave, in absentia or terminated, you will need to vacate your locker.
 
If you will not be renewing your locker, please let me know. I can make arrangements for your library materials to be returned.
   
Please contact me if you have any questions or problems. Thank you.
   
Sylvia Swain
Lewis Library Coordinator258-3267

Your locker privileges expire on <%= @assignment.expiration_date %>. If you would like to renew your locker, please email [lewislib@Princeton.edu](mailto:lewislib@Princeton.edu) Please remember if your status changes during the year from enrolled to on leave, in absentia or terminated, you will need to vacate your locker.
 
If you will not be renewing your locker, please let me know. I can make arrangements for your library materials to be returned.
Please contact me if you have any questions or problems. Thank you.
Sylvia Swain
Lewis Library Coordinator
609-258-3267

2023-03-09 20:35 UTC, kevinreiss commented on app/views/user_mailer/lewis_locker_renewal.text.erb
> +Hi,
Use the text as my earlier comment.

2023-03-14 16:43 UTC, sandbergja approved these changes
🎉  Looks great, thanks @rladdusaw !

2023-03-14 16:43 UTC, sandbergja commented on config/environments/development.rb
> +
Thanks for adding this!

2023-03-14 16:44 UTC, merged