Email users to check if they would like to renew
pulibrary/lockers_and_study_spaces pull request #87
Opened 2022-05-27 19:53 UTC by sandbergja

closes #66

2022-05-28 15:12 UTC, sandbergja commented
Checked this morning to see if this had sent correctly from the staging server.  For some reason, the crontab entry didn't seem to work this morning.  Running the rake task manually on the server seemed to work, but I only saw a single email in the mailcatcher, rather than multiple ones.  Also, the html email template needs some work.

2022-06-21 22:35 UTC, kevinreiss requested changes
Looks good. Just noticed one file that we don't seem to need.

2022-06-22 18:23 UTC, sandbergja commented
@kevinreiss thanks!  I squashed the commits, and removed that scaffold-generated file.

2022-07-07 16:27 UTC, kevinreiss approved these changes

2022-07-07 16:27 UTC, merged